name: mern-project
services:
  frontend:
    init: true
    image: image_mern-project_client_dev
    container_name: frontend_dev
    build:
      context: ./
      dockerfile: ./packages/client/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./packages/client
        target: /var/www/packages/client
      - type: volume
        target: /var/www/packages/client/node_modules
  server:
    container_name: backend_dev
    image: image_mern-project_server_dev
    build:
      context: ./
      dockerfile: ./packages/server/Dockerfile
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./packages/server
        target: /var/www/packages/server
      - type: volume
        target: /var/www/packages/server/node_modules
